name: Selenium testing on UTS website
#testing

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

  steps: 
  - name: checkout
   uses: actions/checkout@v3

  - name: setting up python
    uses: actions/setup-python@v4
    with:
      python-version: 3.11
    
  - name: installing selenium
    run: pip install selenium

  - name: run python script
    run: python3 test_firefox.py
